#########################################################################
#									#
# Author: Copyright (C) 2019, 2021-2023, 2026  Mark Grant		#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
#	AutoMake script file to run tests under make check.		#
#									#
#########################################################################


TESTS = ../tests/shellcheck/run-dot-sh-dot-in-pattern.sh
TESTS += ../prg/c/src/test-bstree/bstreetest01b.sh
TESTS += ../prg/c/src/test-bstree/bstreetest02d.sh
TESTS += ../prg/c/src/test-bstree/bstreetest03f.sh
TESTS += ../prg/c/src/test-bstree/bstreetest04h.sh
TESTS += ../prg/c/src/test-bstree/bstreetest05j.sh
TESTS += ../prg/c/src/test-bstree/bstreetest06l.sh
TESTS += ../prg/c/src/test-bstree/bstreetest07n.sh
TESTS += ../prg/c/src/test-bstree/bstreetest08p.sh
TESTS += ../prg/c/src/test-bstree/bstreetest09r.sh
TESTS += ../prg/c/src/test-bstree/bstreetest10t.sh
TESTS += ../prg/c/src/test-buf-msg/bufmsgtest
TESTS += ../prg/c/src/test-dllist/dllisttest
TESTS += ../prg/c/src/test-errno/errnotest
TESTS += ../prg/c/src/test-sllist/sllisttest01.sh
TESTS += ../prg/c/src/test-sllist/sllisttest02.sh
TESTS += ../prg/c/src/test-sllist/sllisttest03.sh
TESTS += ../prg/c/src/test-sllist/sllisttest04.sh
TESTS += ../prg/c/src/test-sllist/sllisttest05.sh
TESTS += ../prg/c/src/test-headers/compile-headers.sh

